### ISSUE TITLE
Even after logging in the User profile shows Login options

### ISSUE THREAD

**Issue by Aryan1982** [yaredow/Konjo-Habesha-Fashion#2]
![image](https://github.com/yaredow/Konjo-Habesha-Fashion/assets/62349184/8ed69be7-de86-49a0-a3a3-a88a1c324ff8)

![image](https://github.com/yaredow/Konjo-Habesha-Fashion/assets/62349184/22dad42e-4ca2-4a4b-948e-3e5c4802cc7e)

**Comment by yaredow** [comment]
Are you sure? I tried it right now and that is not the case. It has to navigate to the products page after logging in.

**Comment by Aryan1982** [comment]
Yea it does navigate me to products page, but after I clicked to profile it gives me login options. theres no bug, Its build Like that only, I think it would be better to add a profile or something, so user will know that he is already logged in.

**Comment by yaredow** [comment]
> Yea it does navigate me to products page, but after I clicked to profile it gives me login options. theres no bug, Its build Like that only, I think it would be better to add a profile or something, so user will know that he is already logged in.

Got you! You are right! I will add that functionality. I haven't finished the project yet. Thank you for your invaluable comments.  I deleted my previous comment because I didn't understand what you meant first.
